kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 9090
    hostPort: 9090 # Not a typo, testing setting a non-default port
    listenAddress: "127.0.0.1"
    protocol: TCP 
