apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "kube-ingress-proxy.fullname" . }}
  labels:
    {{- include "kube-ingress-proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kube-ingress-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-ingress-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-ingress-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      {{- with .Values.extraInitContainers }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - --listen={{ .Values.listenAddress }}:8080
          - --all-namespaces={{ .Values.rbac.allNamespaces }}
          {{- range .Values.rbac.namespaces }}
          - --namespaces={{ . }}
          {{- end }}
          {{- range .Values.controllerAddresses }}
          - --ingress-class-address={{ .className }}={{ .address }}
          {{- end }}
          {{- with .Values.logVerbosity }}
          - --v={{ . }} 
          {{- end }}
          {{- with .Values.extraArgs }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
          env:
          {{- with .Values.extraEnv }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
              {{- if .Values.hostPort.enabled }}
              hostPort: {{ .Values.hostPort.port }}
              {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- with .Values.extraVolumesMounts }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
      {{- with .Values.extraContainers }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- with .Values.extraVolumes }}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
