{{- if .Values.rbac.create }}
{{/* TODO: Allow specific namespaces */}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-ingress-proxy.fullname" . }}
  labels:
    {{- include "kube-ingress-proxy.labels" . | nindent 4 }}
rules:
- apiGroups: [networking.k8s.io]
  resources: [ingresses]
  verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-ingress-proxy.fullname" . }}
  labels:
    {{- include "kube-ingress-proxy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-ingress-proxy.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-ingress-proxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
