{{- if .Values.rbac.create }}
{{- $namespaces := list "" }}
{{- $roleKind := "ClusterRole" }}
{{- $roleBindingKind := "ClusterRoleBinding" }}
{{- if not .Values.rbac.allNamespaces }}
{{- $namespaces = .Values.rbac.namespaces }}
{{- $roleKind = "Role" }}
{{- $roleBindingKind = "RoleBinding" }}
{{- end }}
{{- range $namespace := $namespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $roleKind }}
metadata:
  name: {{ include "kube-ingress-proxy.fullname" $ }}
  namespace: {{ $namespace }}
  labels:
    {{- include "kube-ingress-proxy.labels" $ | nindent 4 }}
rules:
- apiGroups: [networking.k8s.io]
  resources: [ingresses]
  verbs: [get, list, watch]
{{- if $.Values.istio.enabled }}
- apiGroups: [networking.istio.io]
  resources: [virtualservices]
  verbs: [get, list, watch]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $roleBindingKind }}
metadata:
  name: {{ include "kube-ingress-proxy.fullname" $ }}
  namespace: {{ $namespace }}
  labels:
    {{- include "kube-ingress-proxy.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ $roleKind }}
  name: {{ include "kube-ingress-proxy.fullname" $ }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-ingress-proxy.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
---
{{- end }}
{{- end }}
